# theme: jekyll-theme-cayman

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daily-Mari
email: mvaladez964@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 My blog is about anyting intersting and funny that happens to me in my daily life.
baseurl: "/daily-Mari" # the subpath of your site, e.g. /blog
url: "https://daily-mari.github.io/Daily-Mari/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: @m_palomino12
# github_username:  @daily-mari

# Build settings
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
